[package]
name = "recursion"
version = "0.1.0"
edition = "2021"
default-run = "fibonacci"

[[bin]]
name = "factorial"
path = "src/bin/factorial.rs"

[[bin]]
name = "fibonacci"
path = "src/bin/fibonacci.rs"

[dependencies]
